#!/usr/bin/env bash
# rotate-cf-tokens.sh — the ONLY reader of CF_DEV_TOKEN in this repo.
#
# Mints short-lived, scoped Cloudflare API children for this project from the
# minter token stored in ~/dev/.env. Emits per-purpose env files under
# .cf-tokens.local/ (gitignored) that deploy and migrate scripts source.
#
# Invariants (see ~/.claude/CLAUDE.md "Cloudflare Token Doctrine"):
#   - CF_DEV_TOKEN is account-owned (cfat_*) and never aliased to
#     CLOUDFLARE_API_TOKEN outside this script.
#   - Permission-group GUIDs are looked up at runtime, not hardcoded.
#   - Previous generation of a child is revoked after the new one is minted.
#   - State file .cf-tokens.local/state.json persists token ids for revocation.
#
# Usage:
#   bash scripts/rotate-cf-tokens.sh                  # mint/rotate all children
#   bash scripts/rotate-cf-tokens.sh --list           # show current state
#   bash scripts/rotate-cf-tokens.sh --revoke-all     # revoke every tracked child
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="$ROOT_DIR/.cf-tokens.local"
STATE_FILE="$STATE_DIR/state.json"
ENV_FILE="${CF_DEV_ENV_FILE:-$HOME/dev/.env}"

log()  { printf '[rotate-cf] %s\n' "$*"; }
die()  { printf '[rotate-cf] error: %s\n' "$*" >&2; exit 1; }

# --- Guard rails --------------------------------------------------------

[ "${CLOUDFLARE_API_TOKEN:-}" = "" ] \
  || die "CLOUDFLARE_API_TOKEN is set in the environment. This script refuses to run when an ambient deploy token is already exported (alias violation). Unset it first."

[ -f "$ENV_FILE" ] || die "minter env file not found at $ENV_FILE (override with CF_DEV_ENV_FILE=)"

# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a

[ -n "${CF_DEV_TOKEN:-}" ]          || die "CF_DEV_TOKEN missing from $ENV_FILE"
[ -n "${CLOUDFLARE_ACCOUNT_ID:-}" ] || die "CLOUDFLARE_ACCOUNT_ID missing from $ENV_FILE"

command -v jq   >/dev/null || die "jq is required"
command -v curl >/dev/null || die "curl is required"

mkdir -p "$STATE_DIR"
chmod 700 "$STATE_DIR"
[ -f "$STATE_FILE" ] || echo '{"children": []}' > "$STATE_FILE"

API="https://api.cloudflare.com/client/v4"
ACCT="$CLOUDFLARE_ACCOUNT_ID"
AUTH_MINTER=(-H "Authorization: Bearer $CF_DEV_TOKEN")

# --- Helpers ------------------------------------------------------------

cf_check() {
  local resp="$1" label="$2"
  if ! echo "$resp" | jq -e '.success == true' >/dev/null; then
    printf '[rotate-cf] %s failed:\n%s\n' "$label" "$resp" >&2
    exit 1
  fi
}

# Look up permission-group GUID by exact name.
pg_id() {
  local name="$1"
  jq -r --arg n "$name" '.result[] | select(.name == $n) | .id' "$STATE_DIR/perm-groups.json" \
    | head -n1 | tr -d '\n'
}

# Revoke a token by id via the minter.
revoke_child() {
  local id="$1"
  [ -n "$id" ] || return 0
  local resp
  resp="$(curl -sS -X DELETE "${AUTH_MINTER[@]}" "$API/accounts/$ACCT/tokens/$id")"
  if echo "$resp" | jq -e '.success == true' >/dev/null; then
    log "revoked prior child $id"
  else
    # 400 "token not found" etc. is tolerable during rotation
    log "revoke of $id returned: $(echo "$resp" | jq -c '.errors')"
  fi
}

# Mint a child and return the new record as JSON: {name,id,value,expires_on,created_at}.
#
# Scope resolution:
#   - Account-scoped (default): resources = {"com.cloudflare.api.account.<acct>": "*"}
#   - Zone-scoped: pass a zone id as $3; resources = {"com.cloudflare.api.account.zone.<zid>": "*"}
#     Zone-scoped children cannot touch account-level APIs — they are for zone ops only.
mint_child() {
  # Positional contract (always 3 fixed + variadic):
  #   $1 name   $2 expires_on   $3 zone_id (empty string = account scope)   $4+ perm-group ids
  local name="$1" expires_on="$2" zone_id="$3"
  shift 3
  local perm_ids_json
  perm_ids_json="$(printf '%s\n' "$@" | jq -R '{id: .}' | jq -s .)"

  local resources_json
  if [ -n "$zone_id" ]; then
    resources_json="$(jq -n --arg zid "$zone_id" '{("com.cloudflare.api.account.zone." + $zid): "*"}')"
  else
    resources_json="$(jq -n --arg acct "$ACCT" '{("com.cloudflare.api.account." + $acct): "*"}')"
  fi

  local body
  body="$(jq -n --arg name "$name" --arg exp "$expires_on" \
    --argjson res "$resources_json" --argjson pgs "$perm_ids_json" '
    {
      name: $name,
      policies: [
        {
          effect: "allow",
          resources: $res,
          permission_groups: $pgs
        }
      ],
      expires_on: $exp
    }')"

  local resp
  resp="$(curl -sS -X POST "${AUTH_MINTER[@]}" -H "Content-Type: application/json" \
    --data "$body" "$API/accounts/$ACCT/tokens")"
  cf_check "$resp" "mint $name"

  echo "$resp" | jq -c '{name: .result.name, id: .result.id, value: .result.value,
                         expires_on: .result.expires_on, created_at: now | todate}'
}

# Write a sourceable env file for a child.
write_env() {
  local name="$1" value="$2"
  local out="$STATE_DIR/$name.env"
  umask 077
  cat > "$out" <<EOF
# Generated by scripts/rotate-cf-tokens.sh — do not edit.
# Child: $name (mint ${CHILD_NOW:-$(date -u +%FT%TZ)})
export CLOUDFLARE_API_TOKEN="$value"
export CLOUDFLARE_ACCOUNT_ID="$ACCT"
EOF
  chmod 600 "$out"
  log "wrote $out"
}

# Update state file: append new record, mark old id as revoked.
persist_child() {
  local record="$1"
  local name id
  name="$(echo "$record" | jq -r .name)"
  id="$(echo "$record"   | jq -r .id)"
  # Strip the secret before persisting.
  local safe
  safe="$(echo "$record" | jq 'del(.value)')"
  jq --arg name "$name" --argjson rec "$safe" '
    .children = ((.children // []) | map(select(.name != $name))) + [$rec]
  ' "$STATE_FILE" > "$STATE_FILE.tmp" && mv "$STATE_FILE.tmp" "$STATE_FILE"
  log "persisted state for $name (id=$id)"
}

# --- Subcommands --------------------------------------------------------

if [ "${1:-}" = "--list" ]; then
  jq . "$STATE_FILE"
  exit 0
fi

if [ "${1:-}" = "--revoke-all" ]; then
  log "revoking every tracked child"
  failed=()
  revoked=()
  while read -r id; do
    [ -z "$id" ] && continue
    resp="$(curl -sS -X DELETE "${AUTH_MINTER[@]}" "$API/accounts/$ACCT/tokens/$id")"
    if echo "$resp" | jq -e '.success == true' >/dev/null; then
      log "revoked $id"
      revoked+=("$id")
    else
      log "revoke failed for $id: $(echo "$resp" | jq -c '.errors')"
      failed+=("$id")
    fi
  done < <(jq -r '.children[].id' "$STATE_FILE")

  # Only drop successfully-revoked children from state. Anything that
  # failed (network blip, API 5xx, permission change) stays tracked so
  # a retry can target it.
  jq --argjson ok "$(printf '%s\n' "${revoked[@]}" | jq -R . | jq -s .)" '
    .children = ((.children // []) | map(select([.id] | inside($ok) | not)))
  ' "$STATE_FILE" > "$STATE_FILE.tmp" && mv "$STATE_FILE.tmp" "$STATE_FILE"

  if [ "${#failed[@]}" -gt 0 ]; then
    log "partial failure — ${#failed[@]} children left tracked: ${failed[*]}"
    exit 1
  fi
  log "done"
  exit 0
fi

# --- Mint / rotate ------------------------------------------------------

log "caching permission-groups catalog"
curl -sS "${AUTH_MINTER[@]}" "$API/accounts/$ACCT/tokens/permission_groups" \
  > "$STATE_DIR/perm-groups.json"
cf_check "$(cat "$STATE_DIR/perm-groups.json")" "permission-groups list"

PG_ACCOUNT_SETTINGS_READ="$(pg_id 'Account Settings Read')"
PG_D1_WRITE="$(pg_id 'D1 Write')"
PG_WORKERS_SCRIPTS_WRITE="$(pg_id 'Workers Scripts Write')"
PG_DNS_WRITE="$(pg_id 'DNS Write')"

[ -n "$PG_ACCOUNT_SETTINGS_READ" ]   || die "could not resolve 'Account Settings Read' permission-group"
[ -n "$PG_D1_WRITE" ]                || die "could not resolve 'D1 Write' permission-group"
[ -n "$PG_WORKERS_SCRIPTS_WRITE" ]   || die "could not resolve 'Workers Scripts Write' permission-group"
[ -n "$PG_DNS_WRITE" ]               || die "could not resolve 'DNS Write' permission-group"

# Zones this repo operates on. Add more as subdomains/surfaces grow.
ZONE_JKCA_ME="08e87b3b4b8c0ef0181abfa87499437b"

# Expiry: 90d for worker-deploy, 30d for d1-migrate.
if date -u -v+90d >/dev/null 2>&1; then
  EXP_90D="$(date -u -v+90d +%FT%TZ)"
  EXP_30D="$(date -u -v+30d +%FT%TZ)"
else
  EXP_90D="$(date -u -d '+90 days' +%FT%TZ)"
  EXP_30D="$(date -u -d '+30 days' +%FT%TZ)"
fi
CHILD_NOW="$(date -u +%FT%TZ)"
export CHILD_NOW

rotate() {
  local name="$1" expires_on="$2"
  shift 2
  # Revoke prior generation if tracked.
  local old_id
  old_id="$(jq -r --arg n "$name" '.children[] | select(.name == $n) | .id' "$STATE_FILE" | head -n1)"
  if [ -n "$old_id" ] && [ "$old_id" != "null" ]; then
    revoke_child "$old_id"
  fi
  log "minting $name (expires $expires_on)"
  local record value
  record="$(mint_child "$name" "$expires_on" "" "$@")"
  value="$(echo "$record" | jq -r .value)"
  write_env "$name" "$value"
  persist_child "$record"
}

# Zone-scoped variant — resource is a single zone id, not the account.
rotate_zone() {
  local name="$1" expires_on="$2" zone_id="$3"
  shift 3
  local old_id
  old_id="$(jq -r --arg n "$name" '.children[] | select(.name == $n) | .id' "$STATE_FILE" | head -n1)"
  if [ -n "$old_id" ] && [ "$old_id" != "null" ]; then
    revoke_child "$old_id"
  fi
  log "minting $name (zone=$zone_id, expires $expires_on)"
  local record value
  record="$(mint_child "$name" "$expires_on" "$zone_id" "$@")"
  value="$(echo "$record" | jq -r .value)"
  write_env "$name" "$value"
  persist_child "$record"
}

rotate "whl-worker-deploy" "$EXP_90D" \
  "$PG_WORKERS_SCRIPTS_WRITE" "$PG_ACCOUNT_SETTINGS_READ"
rotate "whl-d1-migrate" "$EXP_30D" \
  "$PG_D1_WRITE" "$PG_ACCOUNT_SETTINGS_READ"
rotate_zone "whl-dns-manage" "$EXP_90D" "$ZONE_JKCA_ME" \
  "$PG_DNS_WRITE"

log "rotation complete"
log "source .cf-tokens.local/whl-worker-deploy.env for deploys"
log "source .cf-tokens.local/whl-d1-migrate.env   for D1 migrate/create"
log "source .cf-tokens.local/whl-dns-manage.env   for DNS record management on jkca.me"
